//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_to_collections
    {
        public short linkID { get; set; }
        public byte addressID { get; set; }
        public byte collectionID { get; set; }
        public bool isActive { get; set; }
    
        public virtual collection collection { get; set; }
    }
}
