//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminExceptionDecision
    {
        public int ID { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> orderitemID { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
