//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEXTR
    {
        public string VendorNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Collection { get; set; }
        public string ParentCode { get; set; }
        public string SubCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Memo { get; set; }
    }
}
