//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVEND
    {
        public string VendorNumber { get; set; }
        public string VendorName { get; set; }
        public string VendorAddr1 { get; set; }
        public string VendorAddr2 { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorZip { get; set; }
        public string VendorPhone { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string AlphaSort { get; set; }
        public string DocumentGroup { get; set; }
        public string VendorClass { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> LastInvoiceDate { get; set; }
        public Nullable<System.DateTime> HighestBalanceDate { get; set; }
        public string TermsCode { get; set; }
        public Nullable<decimal> MTDInvoices { get; set; }
        public Nullable<decimal> MTDPayments { get; set; }
        public Nullable<decimal> MTDDiscounts { get; set; }
        public Nullable<decimal> YTDInvoices { get; set; }
        public Nullable<decimal> YTDPayments { get; set; }
        public Nullable<decimal> YTDDiscounts { get; set; }
        public Nullable<decimal> PYRInvoices { get; set; }
        public Nullable<decimal> PYRPayments { get; set; }
        public Nullable<decimal> PYRDiscounts { get; set; }
        public string GLGroup { get; set; }
        public string LeadTime { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> HighestBalance { get; set; }
        public string OnHold { get; set; }
        public string PermStatus { get; set; }
        public string Internet { get; set; }
        public string BarCode { get; set; }
        public string SecondarySort { get; set; }
        public string EmailAddress { get; set; }
        public string IntlPhone { get; set; }
        public string IntlFax { get; set; }
        public string POEmail { get; set; }
    }
}
