//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCCPT
    {
        public string CustomerNumber { get; set; }
        public string Collection { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PercentOff { get; set; }
    }
}
