//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCUST
    {
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string SortKey { get; set; }
        public string ShipTo { get; set; }
        public string CustomerClass { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string TermsCode { get; set; }
        public string TaxCode { get; set; }
        public string PriceLevel { get; set; }
        public string BuyingGroupCode { get; set; }
        public string GeneralLedgerGroup { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> HighestBalance { get; set; }
        public Nullable<decimal> BadDebtBalance { get; set; }
        public string Message { get; set; }
        public string Hold { get; set; }
        public string StoreOrderHistory { get; set; }
        public string PermanentTemporary { get; set; }
        public string StatementCode { get; set; }
        public string StoreSalesHistory { get; set; }
        public string StorePaymentHistory { get; set; }
        public string ReceiveDunLetters { get; set; }
        public string LastDunLetterSent { get; set; }
        public Nullable<decimal> ServiceChargeGracePeriod { get; set; }
        public string PasswordDesignation { get; set; }
        public string EyefinityCustomer { get; set; }
        public string EcommerceCustomer { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateLastSale { get; set; }
        public Nullable<System.DateTime> DateLastPayment { get; set; }
        public Nullable<System.DateTime> DateHighestPayment { get; set; }
        public Nullable<System.DateTime> DateLastDunLetter { get; set; }
        public string TaxExemptNumber { get; set; }
        public string ShipVia { get; set; }
        public string BuyingGroupCustomer { get; set; }
        public string PricingGroupCustomer { get; set; }
        public string FirstAliasName { get; set; }
        public string FaxNumber { get; set; }
        public string AllowAutoCreditMemoApplication { get; set; }
        public string CountryCode { get; set; }
        public string PromotionalCode { get; set; }
        public string WorkOrderPrinter { get; set; }
        public string InsideSalesperson { get; set; }
        public string C9thColumnPriceCheckExclusion { get; set; }
        public Nullable<decimal> PartsPercentage { get; set; }
        public string FreightCollectPrepaid { get; set; }
        public string PayCommissions { get; set; }
        public string ChargeFreightOnBackorders { get; set; }
        public string SalesClass1 { get; set; }
        public string SalesClass2 { get; set; }
        public string SalesClass3 { get; set; }
        public string SalesClass4 { get; set; }
        public string SalesClass5 { get; set; }
        public string ListPrice { get; set; }
        public string FrameBuyer { get; set; }
        public string Salutation { get; set; }
        public string ShowPrices { get; set; }
        public string SendtoRetailLocator { get; set; }
        public string WebAccountNumber { get; set; }
        public string WebAddress { get; set; }
        public string ReducedCredit { get; set; }
        public string OpportunityBuyType { get; set; }
        public string UseConversionRate { get; set; }
        public string RoyaltyClassCode { get; set; }
        public string SalesCategory { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<System.DateTime> ReactivatedDate { get; set; }
        public string NewReactivatedCode1 { get; set; }
        public string NewReactivatedCode2 { get; set; }
        public string ARCollectionCode { get; set; }
        public string C2ndCopyInvoice { get; set; }
        public string CustomerType { get; set; }
        public string Patterns { get; set; }
        public string DumptoCALLERIDFile { get; set; }
        public string DefaultInvoicePrinter { get; set; }
        public string DefaultCreditMemoPrinter { get; set; }
        public Nullable<decimal> MtdSalesDollars { get; set; }
        public Nullable<decimal> MtdCostsDollars { get; set; }
        public Nullable<decimal> YtdSalesDollars { get; set; }
        public Nullable<decimal> YtdCostsDollars { get; set; }
        public Nullable<decimal> PyrSalesDollars { get; set; }
        public Nullable<decimal> PyrCostsDollars { get; set; }
        public string Consignment { get; set; }
        public string Note { get; set; }
        public string ShipCases { get; set; }
        public Nullable<System.DateTime> LastStockOrderDate { get; set; }
    }
}
