//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AROPEN
    {
        public string CustomerNumber { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentContinuationNumber { get; set; }
        public string TransactionType { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> OriginalCost { get; set; }
        public Nullable<decimal> OriginalDiscount { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public Nullable<decimal> CurrentDiscount { get; set; }
        public string ShipToNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DiscountDueDate { get; set; }
        public string EntryPeriod { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> LastSequenceNumber { get; set; }
        public Nullable<decimal> RegisterNumber { get; set; }
    }
}
