//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSHIP
    {
        public string CustomerNumber { get; set; }
        public string ShipTo { get; set; }
        public string ShipToName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string PhoneNumber { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string TaxCode { get; set; }
        public string ShipVia { get; set; }
        public string TaxExemptNumber { get; set; }
        public string CVCCustomerNumber { get; set; }
        public string SendToRetailLocator { get; set; }
        public string WebAccountNumber { get; set; }
        public string CallerIDFile { get; set; }
        public string RetailName { get; set; }
        public string RetailAddressLine1 { get; set; }
        public string RetailAddressLine2 { get; set; }
    }
}
