//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSVIA
    {
        public string ShipVia { get; set; }
        public string Description { get; set; }
        public string Zone { get; set; }
        public string ShipperNo { get; set; }
        public string SatDelivery { get; set; }
        public string DollarLimit { get; set; }
        public string WeightLimit { get; set; }
        public string Days { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public string Traceable { get; set; }
        public string Guaranteed { get; set; }
        public string CutoffTime { get; set; }
        public string StandardMethod { get; set; }
    }
}
