//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTRAN
    {
        public string CustomerNumber { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentContinuationNumber { get; set; }
        public string SequenceNumber { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionPeriod { get; set; }
        public string Memo { get; set; }
    }
}
