//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBX_Order_Log
    {
        public string order_no { get; set; }
        public Nullable<bool> is_processed { get; set; }
        public Nullable<decimal> lines { get; set; }
    }
}
