//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Like_Collection
    {
        public int id { get; set; }
        public int like_id { get; set; }
        public string icon_image { get; set; }
        public string icon_hover { get; set; }
        public string about { get; set; }
        public string about_image { get; set; }
    }
}
