//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Home_Images
    {
        public int id { get; set; }
        public string link { get; set; }
        public string main_text { get; set; }
        public string sub_text { get; set; }
        public string image { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> rank { get; set; }
    }
}
