//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Blogs
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string main_image { get; set; }
        public string title { get; set; }
        public string sub_image { get; set; }
        public string sub_image_caption { get; set; }
        public string text { get; set; }
        public Nullable<bool> enabled { get; set; }
    }
}
