//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection2
    {
        public string Collection1 { get; set; }
        public string Description { get; set; }
        public string PrintonStyleRankingReport { get; set; }
        public string ConsolidationCode { get; set; }
        public Nullable<decimal> LocatorADollarMinimum { get; set; }
        public Nullable<decimal> LocatorBDollarMinimum { get; set; }
        public Nullable<decimal> LocatorCDollarMinimum { get; set; }
        public Nullable<decimal> LocatorDDollarMinimum { get; set; }
        public string IncludeinFrameBag { get; set; }
        public string IncludeonPriceList { get; set; }
        public string Branded { get; set; }
        public string Active { get; set; }
        public string Coordinator { get; set; }
        public string KenmarkWebsite { get; set; }
        public string EyefinityWebsite { get; set; }
        public string TOSInclusion { get; set; }
        public string RetailLocatorColl { get; set; }
        public string RetailLocator { get; set; }
        public string MedicalGeneral { get; set; }
        public string PriceLevels { get; set; }
        public Nullable<decimal> BuyIn { get; set; }
        public string STRequired { get; set; }
        public Nullable<decimal> RetailLocatorMinimum { get; set; }
        public string LikeCollection { get; set; }
        public Nullable<decimal> Pct_off_Whlsle { get; set; }
        public string Designer { get; set; }
        public Nullable<decimal> LowInventory { get; set; }
        public Nullable<decimal> Ranking { get; set; }
        public string Type { get; set; }
        public string PriceCollection { get; set; }
        public string RetailCollection { get; set; }
        public Nullable<decimal> MaxPctPOP { get; set; }
        public Nullable<decimal> MaxPctIncentive { get; set; }
        public string BestSellers { get; set; }
        public string SpecialMessages { get; set; }
    }
}
