//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public collection()
        {
            this.address_to_collections = new HashSet<address_to_collections>();
        }
    
        public byte collectionID { get; set; }
        public string collectionName { get; set; }
        public string code { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<address_to_collections> address_to_collections { get; set; }
    }
}
