//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_codes
    {
        public byte cid { get; set; }
        public string coll_code { get; set; }
        public int coll_id { get; set; }
        public string coll_name { get; set; }
        public byte sort_order { get; set; }
        public byte is_active { get; set; }
    }
}
