//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_POP
    {
        public int ID { get; set; }
        public string coll_code { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<int> Qty_Limit { get; set; }
        public Nullable<int> collection_frames_needed { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string desc { get; set; }
        public string notes { get; set; }
        public string popid { get; set; }
        public string Qty_On_Hand { get; set; }
        public string Reorder_Message { get; set; }
        public Nullable<int> Package_Qty { get; set; }
        public Nullable<bool> Admin_Only { get; set; }
        public string Show_Qty { get; set; }
        public string New_Accounts_Only { get; set; }
        public string international_price { get; set; }
        public string frame_used { get; set; }
        public string Show_International { get; set; }
    }
}
