//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int content_id { get; set; }
        public string content_key { get; set; }
        public string content_value { get; set; }
        public string content_lang { get; set; }
        public string page { get; set; }
    }
}
