//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public byte countryID { get; set; }
        public string countryNAME { get; set; }
        public string image { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
