//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_shiptos
    {
        public string kenmark_id { get; set; }
        public string shipto_id { get; set; }
        public string customer_name { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string city_state_zip { get; set; }
        public string phone { get; set; }
        public string shipVia { get; set; }
        public string default_shipto_desc { get; set; }
    }
}
