//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSummary
    {
        public string Customer { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Month { get; set; }
        public string Collection { get; set; }
        public decimal GrossSales { get; set; }
        public decimal GrossSalesLY { get; set; }
        public decimal Returns { get; set; }
        public decimal ReturnsLY { get; set; }
        public decimal NetSales { get; set; }
        public decimal NetSalesLY { get; set; }
        public decimal OpenOrders { get; set; }
        public decimal OnlineOrders { get; set; }
    }
}
