//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_purchased
    {
        public string account_num { get; set; }
        public string sku { get; set; }
        public string style { get; set; }
        public Nullable<int> units_purchased { get; set; }
        public string last_purchased { get; set; }
        public Nullable<decimal> price { get; set; }
        public int id { get; set; }
    }
}
