//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustSalesClass
    {
        public string CustSalesClass1 { get; set; }
        public string Description { get; set; }
        public string GLGroup { get; set; }
        public string PayRoyalty { get; set; }
        public string Notes { get; set; }
        public string Active { get; set; }
    }
}
