//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustClass
    {
        public string CustClass1 { get; set; }
        public string Description { get; set; }
        public string GLGroup { get; set; }
        public string ExcludeFromMailings { get; set; }
        public string DumpToCallerIDFile { get; set; }
    }
}
