//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Inventory
    {
        public string kenmarkID { get; set; }
        public string sku { get; set; }
        public Nullable<int> on_hand { get; set; }
        public Nullable<int> add_to_cart { get; set; }
    }
}
