//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customersTest
    {
        public Nullable<int> customer_id { get; set; }
        public string kenmark_id { get; set; }
        public string customer_name { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string default_shipto { get; set; }
        public string default_shipto_desc { get; set; }
        public string phone { get; set; }
        public string ob_type { get; set; }
        public string salesperson_email { get; set; }
        public string order_flag { get; set; }
        public string sales_territory { get; set; }
        public string region { get; set; }
        public string salesperson_name { get; set; }
        public string salesperson_ext { get; set; }
        public string customer_type { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public string on_hold { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string is_monitored { get; set; }
        public string is_inBuyingGroup { get; set; }
        public string term { get; set; }
        public string shipVia { get; set; }
        public string is_international { get; set; }
        public string is_KeyAccount { get; set; }
        public Nullable<int> part_percent { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string proper_address { get; set; }
        public string BuyingGroupName { get; set; }
        public string BuyingGroupAddress1 { get; set; }
        public string BuyingGroupAddress2 { get; set; }
        public string BuyingGroupCityStateZip { get; set; }
        public string is_Consignment { get; set; }
        public string show_prices { get; set; }
        public string isNewReactivated { get; set; }
        public int id { get; set; }
    }
}
