//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class designer_image_order
    {
        public int i_id { get; set; }
        public string designer { get; set; }
        public string image { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string page { get; set; }
    }
}
