//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drawing
    {
        public int s_id { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Company_Name { get; set; }
        public string Street_Address { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Kenmark_ID { get; set; }
        public string Survey_Code { get; set; }
    }
}
