//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int security_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string login { get; set; }
        public string mail { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string MMI { get; set; }
    }
}
