//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int event_id { get; set; }
        public string event_name { get; set; }
        public string display_date { get; set; }
        public System.DateTime event_start_date { get; set; }
        public string location { get; set; }
        public System.DateTime insert_date { get; set; }
        public int inserted_by { get; set; }
        public bool is_active { get; set; }
        public string Booth { get; set; }
    }
}
