//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event1
    {
        public int Event_id { get; set; }
        public string show_name { get; set; }
        public string display_date { get; set; }
        public System.DateTime show_start_date { get; set; }
        public string place { get; set; }
        public System.DateTime insert_date { get; set; }
    }
}
