//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class exception_order_items
    {
        public int exception_id { get; set; }
        public Nullable<int> order_item_id { get; set; }
        public string Exception { get; set; }
        public string Exception_Reasoning { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
