//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameData
    {
        public string UPC { get; set; }
        public string SKU { get; set; }
        public string FrameName { get; set; }
        public string DesignerCollection { get; set; }
        public string Status { get; set; }
        public string ProductGroupType { get; set; }
        public string FrameColorGroup { get; set; }
        public string FrameColorDescription { get; set; }
        public string FrameColorCode { get; set; }
        public string LensColorType { get; set; }
        public string LensColorDescription { get; set; }
        public string EyeSize { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string ED { get; set; }
        public string EDAngle { get; set; }
        public string TempleLength { get; set; }
        public string BridgeSize { get; set; }
        public string DBL { get; set; }
        public string Circumference { get; set; }
        public string GenderType { get; set; }
        public string AgeType { get; set; }
        public string MaterialType { get; set; }
        public string MaterialDescription { get; set; }
        public string PreciousMetalType { get; set; }
        public string PreciousMetalDecription { get; set; }
        public string CountryOfOrigin { get; set; }
        public string TempleType { get; set; }
        public string TempleTypeDescription { get; set; }
        public string BridgeType { get; set; }
        public string BridgeTypeDescription { get; set; }
        public string LenseType { get; set; }
        public string LenseTypeDescription { get; set; }
        public string TrimType { get; set; }
        public string TrimDescription { get; set; }
        public string ClipSunglassType { get; set; }
        public string ClipSunglassDescription { get; set; }
        public string SideshieldsType { get; set; }
        public string SideshieldsDescription { get; set; }
        public string CaseType { get; set; }
        public string CaseTypeDescription { get; set; }
        public string HingeType { get; set; }
        public string RimType { get; set; }
        public string FrameShape { get; set; }
        public string MonthIntroduced { get; set; }
        public string YearIntroduced { get; set; }
        public string CompletePrice { get; set; }
        public string FrontPrice { get; set; }
        public string TemplesPairPrice { get; set; }
        public string TemplesHalfPairPrice { get; set; }
        public string PriceDescription { get; set; }
        public string Features { get; set; }
        public string FramePDType { get; set; }
        public string FramePDDescription { get; set; }
        public string LensVisionType { get; set; }
        public string LensVisionDescription { get; set; }
        public string PatternName { get; set; }
        public string PrescriptionType { get; set; }
        public string PrescriptionDescription { get; set; }
        public string WarrantyType { get; set; }
        public string WarrantyDescription { get; set; }
    }
}
