//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame_Feedback
    {
        public int f_id { get; set; }
        public string lframe_sk { get; set; }
        public Nullable<int> color_rating { get; set; }
        public Nullable<int> shape_rating { get; set; }
        public string comment { get; set; }
        public Nullable<int> security_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string email { get; set; }
    }
}
