//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_ob_inv
    {
        public string sku { get; set; }
        public string upc { get; set; }
        public string new_flag { get; set; }
        public int qty_avail { get; set; }
        public decimal a_1_price { get; set; }
        public decimal a_2_price { get; set; }
        public decimal a_3_price { get; set; }
        public decimal b_1_price { get; set; }
        public decimal b_2_price { get; set; }
        public decimal b_3_price { get; set; }
        public Nullable<int> lframe_sk { get; set; }
        public string style_name { get; set; }
        public string color_name { get; set; }
        public string coll_code { get; set; }
        public string description { get; set; }
        public string coll_name { get; set; }
        public string sort_order { get; set; }
        public string designer_coll { get; set; }
        public string c_1_price { get; set; }
        public string c_2_price { get; set; }
        public string c_3_price { get; set; }
    }
}
