//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_stmts
    {
        public string kenmark_id { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<System.DateTime> invoice_due_date { get; set; }
        public Nullable<decimal> original_invoice_amt { get; set; }
        public Nullable<decimal> current_invoice_amt { get; set; }
    }
}
