//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_VSB_inv
    {
        public string sku { get; set; }
        public string description { get; set; }
        public string upc { get; set; }
        public string coll_name { get; set; }
        public string style_name { get; set; }
        public string color_name { get; set; }
        public string flag { get; set; }
        public string sideshield_flag { get; set; }
        public string sort_order { get; set; }
        public string coll_code { get; set; }
        public string designer_coll { get; set; }
        public string coll_group { get; set; }
        public Nullable<decimal> price { get; set; }
        public string gender { get; set; }
        public string material { get; set; }
        public Nullable<decimal> cust_price { get; set; }
    }
}
