//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_Inventory_Admin_Info
    {
        public string sku { get; set; }
        public Nullable<bool> NLA { get; set; }
        public Nullable<bool> Sale { get; set; }
        public Nullable<bool> CloseOut { get; set; }
        public Nullable<bool> GiftFrame { get; set; }
        public Nullable<bool> ExpiredSale { get; set; }
    }
}
