//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INATTR
    {
        public string Item { get; set; }
        public string ColorGroup { get; set; }
        public string MaterialFront { get; set; }
        public string MaterialTemple { get; set; }
        public string RimType { get; set; }
        public string Decor { get; set; }
        public Nullable<int> AgeStart { get; set; }
        public Nullable<int> AgeEnd { get; set; }
        public string BridgeType { get; set; }
        public string FrameShape { get; set; }
        public Nullable<int> BaseCurve { get; set; }
        public string LensType { get; set; }
        public string LensMaterial { get; set; }
        public string LensCategory { get; set; }
        public string LensColor { get; set; }
        public string TargetDemographic { get; set; }
    }
}
