//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDATA
    {
        public string VendorNumber { get; set; }
        public string Collection { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public string LikeCollection { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
        public Nullable<decimal> QtyOnOrder { get; set; }
        public Nullable<decimal> OnHandCost { get; set; }
        public Nullable<decimal> OnOrderCost { get; set; }
        public Nullable<System.DateTime> ExpectedReceiptDate { get; set; }
        public string ItemClass { get; set; }
    }
}
