//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFrame
    {
        public string Item { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> ReleaseMonths { get; set; }
        public Nullable<decimal> WholesalePrice { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public string UPC { get; set; }
        public string Collection { get; set; }
    }
}
