//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INLEAD
    {
        public string Style { get; set; }
        public string Item { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string PONumber { get; set; }
        public string ReceiptNumber { get; set; }
        public string VendorNumber { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string RegisterNumber { get; set; }
        public Nullable<decimal> QtyOrdered { get; set; }
        public string Collection { get; set; }
        public string LikeCollection { get; set; }
    }
}
