//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INMAST
    {
        public string Style { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string ItemClass { get; set; }
        public string SmallestUOM { get; set; }
        public string UOM2 { get; set; }
        public string UOM3 { get; set; }
        public string InventoryUOM { get; set; }
        public string PricingUOM { get; set; }
        public string SellingUOM { get; set; }
        public string CostingUOM { get; set; }
        public string BuyingUOM { get; set; }
        public Nullable<decimal> ConversionFactor2 { get; set; }
        public Nullable<decimal> ConversionFactor3 { get; set; }
        public string AlphaSort { get; set; }
        public string PackageSize { get; set; }
        public Nullable<decimal> CostStandard { get; set; }
        public Nullable<decimal> CostAverage { get; set; }
        public Nullable<decimal> CostLast { get; set; }
        public Nullable<decimal> PurchaseOrderCost { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public string GeneralLedgerGroup { get; set; }
        public string PrimaryVendorNumber { get; set; }
        public string VendorPartNumber { get; set; }
        public Nullable<System.DateTime> DateLastSale { get; set; }
        public Nullable<System.DateTime> DateLastPurchase { get; set; }
        public Nullable<System.DateTime> DateLastPriceChange { get; set; }
        public Nullable<System.DateTime> DateLastCostChange { get; set; }
        public string Taxable { get; set; }
        public string UpdateInventory { get; set; }
        public string InputDescription { get; set; }
        public string MiscellaneousSales { get; set; }
        public Nullable<decimal> WeightInventoryUOM { get; set; }
        public Nullable<decimal> WeightSellingUOM { get; set; }
        public Nullable<decimal> WeightBuyingUOM { get; set; }
        public string FreightClassification { get; set; }
        public Nullable<decimal> MtdUnitSalesInventory { get; set; }
        public Nullable<decimal> MtdDollarSales { get; set; }
        public Nullable<decimal> YtdUnitSalesInventory { get; set; }
        public Nullable<decimal> YtdDollarSales { get; set; }
        public Nullable<decimal> PyrUnitSalesInventory { get; set; }
        public Nullable<decimal> PyrDollarSales { get; set; }
        public Nullable<decimal> StandardCommissionPercentage { get; set; }
        public string AppearonTOSReport { get; set; }
        public string AppearonStyleRankingReport { get; set; }
        public string AppearonPriceList { get; set; }
        public string AppearinFramesDataFile { get; set; }
        public string AppearonSuggestedOrderReport { get; set; }
        public string TrackAsGift { get; set; }
        public string PartType { get; set; }
        public string AppearonSalesPortal { get; set; }
        public string Type { get; set; }
        public string UPC { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Discontinued { get; set; }
        public string Sex { get; set; }
        public string Material { get; set; }
        public string SpringHinge { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Collection { get; set; }
        public string Division { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string BagLayout { get; set; }
        public string POCollectionCode { get; set; }
        public string FramesDataSubmission { get; set; }
        public string BreakType1 { get; set; }
        public string BreakType2 { get; set; }
        public Nullable<decimal> PDLevel1 { get; set; }
        public Nullable<decimal> PDLevel2 { get; set; }
        public Nullable<decimal> PDLevel3 { get; set; }
        public Nullable<decimal> PDLevel4 { get; set; }
        public Nullable<decimal> PDLevel5 { get; set; }
        public Nullable<decimal> PDLevel6 { get; set; }
        public Nullable<decimal> PDLevel7 { get; set; }
        public Nullable<decimal> PDLevel8 { get; set; }
        public Nullable<decimal> PDLevel9 { get; set; }
        public Nullable<System.DateTime> ExpectedReceiptDate { get; set; }
        public string POPTracking { get; set; }
        public Nullable<System.DateTime> DateRecalled { get; set; }
        public Nullable<System.DateTime> FramesDataSubmitDate { get; set; }
        public Nullable<System.DateTime> WebReleaseDate { get; set; }
        public Nullable<System.DateTime> PhotographyDate { get; set; }
        public Nullable<System.DateTime> CloseoutDate { get; set; }
        public string WebMaterial { get; set; }
        public string WebGender { get; set; }
        public string WebHingeType { get; set; }
        public string WebBridgeType { get; set; }
        public string WebColorCode { get; set; }
        public string WebColorDescription { get; set; }
        public Nullable<decimal> WebPrice { get; set; }
        public Nullable<decimal> WebEye { get; set; }
        public Nullable<decimal> WebA { get; set; }
        public Nullable<decimal> WebB { get; set; }
        public Nullable<decimal> WebED { get; set; }
        public Nullable<decimal> WebDBL { get; set; }
        public Nullable<decimal> WebTempleLength { get; set; }
        public string WebClip { get; set; }
        public string WebSGLens { get; set; }
        public string WebMainImage { get; set; }
        public string WebThumbnail { get; set; }
        public string WebColorImage { get; set; }
        public string WebComments { get; set; }
        public string WebUnused1 { get; set; }
        public string WebUnused2 { get; set; }
        public string IncludeOnPOPCount { get; set; }
        public string CountryOfOrigin { get; set; }
        public string HTSUSCode { get; set; }
        public Nullable<System.DateTime> AnticipatedReleaseDate { get; set; }
        public string CustomerPortal { get; set; }
    }
}
