//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPOP
    {
        public string Style { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> FrameRequirement { get; set; }
        public Nullable<decimal> AutoReorder { get; set; }
        public Nullable<decimal> MonthlyPar { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string Comments { get; set; }
    }
}
