//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InquiryEntities : DbContext
    {
        public InquiryEntities()
            : base("name=InquiryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APEXCD> APEXCDs { get; set; }
        public DbSet<APEXTR> APEXTRs { get; set; }
        public DbSet<APVEND> APVENDs { get; set; }
        public DbSet<ARCCPT> ARCCPTs { get; set; }
        public DbSet<ARCUST> ARCUSTs { get; set; }
        public DbSet<ARNERA> ARNERAs { get; set; }
        public DbSet<AROPEN> AROPENs { get; set; }
        public DbSet<ARSHIP> ARSHIPs { get; set; }
        public DbSet<ARSVIA> ARSVIAs { get; set; }
        public DbSet<ARTerm> ARTerms { get; set; }
        public DbSet<ARTRAN> ARTRANs { get; set; }
        public DbSet<Collection2> INQCollection { get; set; }
        public DbSet<Country2> INQCountry2 { get; set; }
        public DbSet<CustClass> CustClasses { get; set; }
        public DbSet<CustomerSummary> CustomerSummaries { get; set; }
        public DbSet<CustomerSummaryNetSale> CustomerSummaryNetSales { get; set; }
        public DbSet<CustSalesClass> CustSalesClasses { get; set; }
        public DbSet<EODUpdateLog> EODUpdateLogs { get; set; }
        public DbSet<EXDATA> EXDATAs { get; set; }
        public DbSet<FRAME> FRAMEs { get; set; }
        public DbSet<FrameData> FrameDatas { get; set; }
        public DbSet<FramesData> FramesDatas { get; set; }
        public DbSet<GeoRegion> GeoRegions { get; set; }
        public DbSet<INATTR> INATTRs { get; set; }
        public DbSet<INDATA> INDATAs { get; set; }
        public DbSet<INFrame> INFrames { get; set; }
        public DbSet<INItem> INItems { get; set; }
        public DbSet<INLEAD> INLEADs { get; set; }
        public DbSet<INMAST> INMASTs { get; set; }
        public DbSet<INPOP> INPOPs { get; set; }
        public DbSet<InquiryParam> InquiryParams { get; set; }
        public DbSet<INStyle> INStyles { get; set; }
        public DbSet<INQInventory> INQInventories { get; set; }
        public DbSet<INWHSE> INWHSEs { get; set; }
        public DbSet<ItemClass> ItemClasses { get; set; }
        public DbSet<ItemRecall> ItemRecalls { get; set; }
        public DbSet<JuneRecall> JuneRecalls { get; set; }
        public DbSet<KENSAL> KENSALs { get; set; }
        public DbSet<Layout> Layouts { get; set; }
        public DbSet<MasterLayout> MasterLayouts { get; set; }
        public DbSet<MyDateTable> MyDateTables { get; set; }
        public DbSet<NewFrameData> NewFrameDatas { get; set; }
        public DbSet<ORANAL> ORANALs { get; set; }
        public DbSet<ORCTRT> ORCTRTs { get; set; }
        public DbSet<ORDATA> ORDATAs { get; set; }
        public DbSet<ORDER2> ORDERSINQ { get; set; }
        public DbSet<ORDERS2> ORDERS2 { get; set; }
        public DbSet<ORPINA> ORPINAs { get; set; }
        public DbSet<ORPINATemp> ORPINATemps { get; set; }
        public DbSet<ORPINV> ORPINVs { get; set; }
        public DbSet<ORPINV2> ORPINV2 { get; set; }
        public DbSet<ORPINV2Temp> ORPINV2Temp { get; set; }
        public DbSet<ORPINVTemp> ORPINVTemps { get; set; }
        public DbSet<PerformanceSummary> PerformanceSummaries { get; set; }
        public DbSet<PORDR> PORDRS { get; set; }
        public DbSet<PORDRS2> PORDRS2 { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<RegionSummary> RegionSummaries { get; set; }
        public DbSet<SACFAN> SACFANs { get; set; }
        public DbSet<SACFANTemp> SACFANTemps { get; set; }
        public DbSet<SACFA> SACFAS { get; set; }
        public DbSet<SACFASTemp> SACFASTemps { get; set; }
        public DbSet<SACMM> SACMMS { get; set; }
        public DbSet<SACMMSTemp> SACMMSTemps { get; set; }
        public DbSet<SACollection> SACollections { get; set; }
        public DbSet<SACollectionCurrent> SACollectionCurrents { get; set; }
        public DbSet<SACountry> SACountries { get; set; }
        public DbSet<SACountryCurrent> SACountryCurrents { get; set; }
        public DbSet<SACSFN> SACSFNs { get; set; }
        public DbSet<SACSFNTemp> SACSFNTemps { get; set; }
        public DbSet<SACSF> SACSFS { get; set; }
        public DbSet<SACSFSTemp> SACSFSTemps { get; set; }
        public DbSet<SACUSO> SACUSOes { get; set; }
        public DbSet<SACUST> SACUSTs { get; set; }
        public DbSet<SACUST_NEW> SACUST_NEW { get; set; }
        public DbSet<SACustomer> SACustomers { get; set; }
        public DbSet<SACustomerCurrent> SACustomerCurrents { get; set; }
        public DbSet<SADATA> SADATAs { get; set; }
        public DbSet<SADATACurrent> SADATACurrents { get; set; }
        public DbSet<SADATATemp> SADATATemps { get; set; }
        public DbSet<SAFrame> SAFrames { get; set; }
        public DbSet<SAFrameCurrent> SAFrameCurrents { get; set; }
        public DbSet<SAGoal> SAGoals { get; set; }
        public DbSet<SAItem> SAItems { get; set; }
        public DbSet<SAItemCurrent> SAItemCurrents { get; set; }
        public DbSet<Salesperson> Salespersons { get; set; }
        public DbSet<SalespersonSummary> SalespersonSummaries { get; set; }
        public DbSet<SALikeCollection> SALikeCollections { get; set; }
        public DbSet<SALikeCollectionCurrent> SALikeCollectionCurrents { get; set; }
        public DbSet<SARegion> SARegions { get; set; }
        public DbSet<SARegionCurrent> SARegionCurrents { get; set; }
        public DbSet<SASalesperson> SASalespersons { get; set; }
        public DbSet<SASalespersonCurrent> SASalespersonCurrents { get; set; }
        public DbSet<SASCOL> SASCOLs { get; set; }
        public DbSet<SASLSP> SASLSPs { get; set; }
        public DbSet<SASLSPTemp> SASLSPTemps { get; set; }
        public DbSet<SAStyle> SAStyles { get; set; }
        public DbSet<SAStyleCurrent> SAStyleCurrents { get; set; }
        public DbSet<SASummary> SASummaries { get; set; }
        public DbSet<SASummaryTemp> SASummaryTemps { get; set; }
        public DbSet<SASVCR> SASVCRs { get; set; }
        public DbSet<SAVendor> SAVendors { get; set; }
        public DbSet<SAVendorCurrent> SAVendorCurrents { get; set; }
        public DbSet<SLSINV> SLSINVs { get; set; }
        public DbSet<SLSTran> SLSTrans { get; set; }
        public DbSet<SLSTransArchive> SLSTransArchives { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<StockPerformance> StockPerformances { get; set; }
        public DbSet<STYLE> STYLEs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<USRegion> USRegions { get; set; }
        public DbSet<ValidDate> ValidDates { get; set; }
        public DbSet<WebUser> WebUsers { get; set; }
    }
}
