//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_info
    {
        public string sku { get; set; }
        public string style { get; set; }
        public Nullable<int> Eye { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public string ED { get; set; }
        public string DBL { get; set; }
        public string Temples { get; set; }
        public string Circ { get; set; }
        public string Color { get; set; }
        public string Like_Color { get; set; }
        public string Gender { get; set; }
        public string Material { get; set; }
        public string Shape { get; set; }
    }
}
