//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INWHSE
    {
        public string Warehouse { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
        public Nullable<decimal> QtyOnOrder { get; set; }
        public Nullable<decimal> QtyOnCommitted { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> PeriodBeginAmount { get; set; }
        public Nullable<decimal> PeriodReceipts { get; set; }
        public Nullable<decimal> PeriodAdjustments { get; set; }
        public Nullable<decimal> PeriodSales { get; set; }
        public Nullable<decimal> MinStock { get; set; }
        public Nullable<decimal> MaxStock { get; set; }
        public Nullable<decimal> EconomicOrder { get; set; }
        public Nullable<decimal> MTDUnits { get; set; }
        public Nullable<decimal> MTDSales { get; set; }
        public Nullable<decimal> YTDUnits { get; set; }
        public Nullable<decimal> YTDSales { get; set; }
        public Nullable<decimal> PriorYearUnits { get; set; }
        public Nullable<decimal> PriorYearSales { get; set; }
        public Nullable<decimal> YTDAvgOnHand { get; set; }
        public Nullable<decimal> PriorYearAvgOnhand { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public Nullable<decimal> FutureCommitted { get; set; }
    }
}
