//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRecall
    {
        public string Item { get; set; }
        public string Type { get; set; }
        public string Salesperson { get; set; }
        public Nullable<System.DateTime> RecallDate { get; set; }
    }
}
