//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClass
    {
        public string ItemClass1 { get; set; }
        public string Description { get; set; }
        public string DefaultGLGroup { get; set; }
        public string ConsolidationItemClass { get; set; }
        public string ExcludeFromStyleRanking { get; set; }
    }
}
