//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuneRecall
    {
        public string SLS { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> InBag { get; set; }
        public decimal Sold { get; set; }
    }
}
