//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kenmark_Collections_Sub
    {
        public string Group { get; set; }
        public string Sub_Group { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
