//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLayout
    {
        public string Application { get; set; }
        public string ColumnNo { get; set; }
        public string Name { get; set; }
        public string ColumnOrder { get; set; }
        public string Heading { get; set; }
        public string Width { get; set; }
        public string Alignment { get; set; }
        public string Type { get; set; }
        public string Sort { get; set; }
        public string dhtmlxFormat { get; set; }
        public string DefaultVisible { get; set; }
        public string Permissions { get; set; }
        public string xlsFormat { get; set; }
    }
}
