//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_Feedback
    {
        public int id { get; set; }
        public Nullable<int> SID { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
