//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewFrameData
    {
        public int ID { get; set; }
        public string UPC { get; set; }
        public string I { get; set; }
        public string J { get; set; }
        public string O { get; set; }
        public string P { get; set; }
        public string Q { get; set; }
        public string R { get; set; }
        public string S { get; set; }
        public string T { get; set; }
        public string U { get; set; }
        public string V { get; set; }
        public string W { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public string AD { get; set; }
        public string AE { get; set; }
        public string AG { get; set; }
        public string AI { get; set; }
        public string AK { get; set; }
        public string AS { get; set; }
        public string AT { get; set; }
        public string AU { get; set; }
        public string BD { get; set; }
    }
}
