//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ob_qty_breaks
    {
        public int a_1_min { get; set; }
        public int a_1_max { get; set; }
        public int a_2_min { get; set; }
        public int a_2_max { get; set; }
        public int a_3_min { get; set; }
        public int a_3_max { get; set; }
        public int b_1_min { get; set; }
        public int b_1_max { get; set; }
        public int b_2_min { get; set; }
        public int b_2_max { get; set; }
        public int b_3_min { get; set; }
        public int b_3_max { get; set; }
        public Nullable<int> c_1_min { get; set; }
        public Nullable<int> c_1_max { get; set; }
        public Nullable<int> c_2_min { get; set; }
        public Nullable<int> c_2_max { get; set; }
        public Nullable<int> c_3_min { get; set; }
        public Nullable<int> c_3_max { get; set; }
    }
}
