//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORANAL
    {
        public System.DateTime Today { get; set; }
        public Nullable<decimal> OpenSales { get; set; }
        public Nullable<decimal> BOSales { get; set; }
        public Nullable<decimal> OpenKey { get; set; }
        public Nullable<decimal> BOKey { get; set; }
        public Nullable<decimal> OpenIntl { get; set; }
        public Nullable<decimal> BOIntl { get; set; }
        public Nullable<decimal> Inventory { get; set; }
    }
}
