//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCTRT
    {
        public string CustomerNumber { get; set; }
        public string Style { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string LikeCollection { get; set; }
        public string ItemClass { get; set; }
        public string Collection { get; set; }
        public Nullable<System.DateTime> DateLastSale { get; set; }
    }
}
