//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDATA
    {
        public string CustomerNumber { get; set; }
        public string Collection { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public string ItemClass { get; set; }
        public string Salesperson { get; set; }
        public string Region { get; set; }
        public string GeoRegion { get; set; }
        public string USRegion { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zip3 { get; set; }
        public string Branded { get; set; }
        public string Designer { get; set; }
        public Nullable<decimal> OpenUnits { get; set; }
        public Nullable<decimal> BO { get; set; }
        public Nullable<decimal> OpenCost { get; set; }
        public Nullable<decimal> BOCost { get; set; }
        public Nullable<decimal> OpenSales { get; set; }
        public Nullable<decimal> BOSales { get; set; }
        public string VendorNumber { get; set; }
        public string LikeCollection { get; set; }
        public Nullable<decimal> FOpenUnits { get; set; }
        public Nullable<decimal> FBO { get; set; }
        public Nullable<decimal> FOpenCost { get; set; }
        public Nullable<decimal> FBOCost { get; set; }
        public Nullable<decimal> FOpenSales { get; set; }
        public Nullable<decimal> FBOSales { get; set; }
    }
}
