//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS2
    {
        public string OrderNumber { get; set; }
        public string LineNumber { get; set; }
        public string Reason { get; set; }
        public string DefectReasonCode { get; set; }
        public Nullable<decimal> OriginalOrderQty { get; set; }
        public Nullable<decimal> TotalShippedQty { get; set; }
        public Nullable<decimal> TotalAdjustedQty { get; set; }
        public Nullable<decimal> OrderedQtyBalance { get; set; }
        public Nullable<decimal> ShippedQty { get; set; }
        public Nullable<decimal> BOQty { get; set; }
        public string Nonstock { get; set; }
        public string Special { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string Division { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string EyefinityOrderID { get; set; }
        public string EyefinityItemID { get; set; }
        public Nullable<decimal> DiscountPct { get; set; }
        public Nullable<decimal> CommissionPct { get; set; }
        public string ReturnOrAllowance { get; set; }
        public string Warehouse { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string ItemClass { get; set; }
        public string UOMSmallest { get; set; }
        public string UOM2 { get; set; }
        public string UOM3 { get; set; }
        public string UOMInventory { get; set; }
        public string UOMPricing { get; set; }
        public string UOMSelling { get; set; }
        public string UOMCosting { get; set; }
        public string UOMBuying { get; set; }
        public Nullable<decimal> ConvFactorInventory { get; set; }
        public Nullable<decimal> ConvFactorPrice { get; set; }
        public Nullable<decimal> ConvFactorSell { get; set; }
        public Nullable<decimal> ConvFactorCost { get; set; }
        public Nullable<decimal> PackageSize { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public string GLGroup { get; set; }
        public string Vendor { get; set; }
        public string VendorItemNumber { get; set; }
        public string Taxable { get; set; }
        public string UpdateInventory { get; set; }
        public string InputDescription { get; set; }
        public string MiscellaneousSales { get; set; }
        public string UnknownFlag { get; set; }
        public Nullable<decimal> WeightInvUOM { get; set; }
        public Nullable<decimal> WeightSellUOM { get; set; }
        public string FreightClass { get; set; }
        public Nullable<decimal> StandardCommissionPct { get; set; }
        public string Location { get; set; }
        public string Collection { get; set; }
    }
}
