//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_POP_Combination
    {
        public int ID { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> qty { get; set; }
        public string coll_code { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<bool> pop_enabled { get; set; }
    }
}
