//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items_deleted
    {
        public int order_item_id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> lframe_sk { get; set; }
        public string upc { get; set; }
        public string sku { get; set; }
        public string frame_name { get; set; }
        public string k_description { get; set; }
        public System.DateTime create_date { get; set; }
        public string item_notes { get; set; }
        public int quantity { get; set; }
        public string sideshield_flag { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> spec_price { get; set; }
        public Nullable<decimal> price_percent { get; set; }
        public Nullable<decimal> spec_price_percent { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<bool> frame_enabled { get; set; }
        public Nullable<int> ncf_frame { get; set; }
        public string promo_code { get; set; }
        public Nullable<bool> inventory_reduction { get; set; }
        public Nullable<System.DateTime> deleted_time { get; set; }
    }
}
