//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER2
    {
        public string OrderNumber { get; set; }
        public string DocumentType { get; set; }
        public string Status { get; set; }
        public string StatusType { get; set; }
        public string ShippingLabelStatus { get; set; }
        public string CustomerPO { get; set; }
        public string BuyingGroupAcct { get; set; }
        public string SalespersonEMail { get; set; }
        public string FreightFlag { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> NonMedicalTax { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> MiscAmount { get; set; }
        public Nullable<decimal> InvDiscount { get; set; }
        public Nullable<decimal> MedicalTax { get; set; }
        public string CreditMemoInvoice { get; set; }
        public string Reference { get; set; }
        public string PONumber { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public string EnteredBy { get; set; }
        public string InvoicedBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditTim { get; set; }
        public string Memo { get; set; }
        public string ShipTo { get; set; }
        public Nullable<decimal> WeightPounds { get; set; }
        public Nullable<decimal> WeightOunces { get; set; }
        public string Question { get; set; }
        public string OnHold { get; set; }
        public string Terminal { get; set; }
        public string Warehouse { get; set; }
        public string CustomerNumber { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string TermsCode { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string PricingLevel { get; set; }
        public string ShipVia { get; set; }
        public string InvoiceNumber { get; set; }
    }
}
