//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public string order_no { get; set; }
        public int customer_id { get; set; }
        public string shipto_id { get; set; }
        public string customer_po { get; set; }
        public string ship_method { get; set; }
        public string order_notes { get; set; }
        public string email_address { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
        public Nullable<System.DateTime> export_date { get; set; }
        public bool opp_buy { get; set; }
        public string salesperson_territory { get; set; }
        public string promo_code { get; set; }
        public Nullable<bool> has_exceptions { get; set; }
        public Nullable<bool> over_credit_limit { get; set; }
        public Nullable<bool> is_temp_customer { get; set; }
        public Nullable<int> temp_id { get; set; }
        public Nullable<int> temp_ship_id { get; set; }
        public Nullable<bool> is_on_hold { get; set; }
        public Nullable<bool> is_monitored { get; set; }
        public Nullable<bool> needs_patterns { get; set; }
        public string requested_ship_date { get; set; }
        public string term { get; set; }
        public Nullable<int> from_site { get; set; }
        public Nullable<bool> closeout_cases { get; set; }
        public Nullable<bool> isNewReactivated { get; set; }
        public string show_code { get; set; }
        public Nullable<bool> print_to_admin { get; set; }
    }
}
