//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_cases
    {
        public int case_item_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string upc { get; set; }
        public string description { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string sku { get; set; }
        public bool enabled { get; set; }
    }
}
