//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORPINATemp
    {
        public string InvoiceNumber { get; set; }
        public string BilltoName { get; set; }
        public string BilltoAddressLine1 { get; set; }
        public string BilltoAddressLine2 { get; set; }
        public string BilltoAddressLine3 { get; set; }
        public string ShiptoCustomerName { get; set; }
        public string ShiptoAddressLine1 { get; set; }
        public string ShiptoAddressLine2 { get; set; }
        public string ShiptoAddressLine3 { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string CustomerNumber { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
    }
}
