//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORPINV
    {
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string DocumentType { get; set; }
        public string CustomerPONumber { get; set; }
        public string FreightFlag { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> InvoiceDiscount { get; set; }
        public string Reference { get; set; }
        public string CreditCardNumber { get; set; }
        public Nullable<decimal> AmountTendered { get; set; }
        public string PONumber { get; set; }
        public string ShipTo { get; set; }
        public string Warehouse { get; set; }
        public string CustomerNumber { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string TermsCode { get; set; }
        public string TaxCode { get; set; }
        public string ShipVia { get; set; }
        public string OrderNumber { get; set; }
        public string BillTo { get; set; }
        public string DocumentType2 { get; set; }
        public string OrderUser { get; set; }
        public string InvoiceUser { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryTime { get; set; }
        public string SalesType { get; set; }
    }
}
