//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORPINV2Temp
    {
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceLineNumber { get; set; }
        public Nullable<decimal> OriginalOrderedAmount { get; set; }
        public Nullable<decimal> ShippedQuantity { get; set; }
        public Nullable<decimal> BackorderedQuantity { get; set; }
        public string NonstockedItem { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> DiscountAmountByLine { get; set; }
        public string Allowance { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string ItemClass { get; set; }
        public string SmallestUOM { get; set; }
        public string UOM2 { get; set; }
        public string UOM3 { get; set; }
        public string InventoryUOM { get; set; }
        public string PricingUOM { get; set; }
        public string SellingUOM { get; set; }
        public string CostingUOM { get; set; }
        public string BuyingUOM { get; set; }
        public Nullable<decimal> InventoryConversionFactor { get; set; }
        public Nullable<decimal> PriceConversionFactor { get; set; }
        public Nullable<decimal> SellConversionFactor { get; set; }
        public Nullable<decimal> CostConversionFactor { get; set; }
        public string Division { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string SpecialPricingFlag { get; set; }
        public string Collection { get; set; }
    }
}
