//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_logs
    {
        public int PaymentLogID { get; set; }
        public int customer_id { get; set; }
        public int payment_id { get; set; }
        public string TransactionID { get; set; }
        public string ResultCode { get; set; }
        public string CVV2match { get; set; }
        public string ResponseMSG { get; set; }
        public string AuthenticationCode { get; set; }
        public string AVSZipMatch { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime insert_date { get; set; }
    }
}
