//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceSummary
    {
        public string Salesperson { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Month { get; set; }
        public decimal NetSales { get; set; }
        public Nullable<decimal> NetSalesLY { get; set; }
        public decimal StockOrders { get; set; }
        public decimal StockOrdersLY { get; set; }
        public decimal NewAccounts { get; set; }
        public decimal NewAccountsLY { get; set; }
        public decimal Goals { get; set; }
        public decimal Estimate { get; set; }
        public int HasEstimate { get; set; }
        public decimal BonusEligibleNetSales { get; set; }
        public Nullable<decimal> BonusEligibleNetSalesLY { get; set; }
        public string Region { get; set; }
    }
}
