//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORDR
    {
        public string PONumber { get; set; }
        public string DocumentType { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> NumberReceipts { get; set; }
        public string Acknowledgement { get; set; }
        public string Confirmation { get; set; }
        public string Reference { get; set; }
        public string ShipVia { get; set; }
        public string FreightOnBoard { get; set; }
        public string FreightFlag { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> PromisedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public string Buyer { get; set; }
        public string Terms { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddr1 { get; set; }
        public string ShipToAddr2 { get; set; }
        public string ShipToAddr3 { get; set; }
        public string Memo { get; set; }
        public string Customer { get; set; }
        public string Disclaimer { get; set; }
        public string LastReceiptUsed { get; set; }
        public string Vendor { get; set; }
        public string Warehouse { get; set; }
    }
}
