//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORDRS2
    {
        public string PONumber { get; set; }
        public string LineNumber { get; set; }
        public Nullable<decimal> OriginalOrderQty { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> BackorderedQty { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<System.DateTime> DatePromised { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string NonstockItem { get; set; }
        public string VendorItem { get; set; }
        public Nullable<decimal> LeadTimeDays { get; set; }
        public Nullable<decimal> FreightFactor { get; set; }
        public string FactorBasis { get; set; }
        public Nullable<decimal> NormalCost { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string ItemClass { get; set; }
        public string UOMInventory { get; set; }
        public string UOMBuying { get; set; }
        public string UOMCosting { get; set; }
        public Nullable<decimal> ConvFactorInventory { get; set; }
        public Nullable<decimal> ConvFactorBuying { get; set; }
        public Nullable<decimal> ConvFactorCosting { get; set; }
        public string GLGroup { get; set; }
        public string Taxable { get; set; }
        public string UpdateInventory { get; set; }
        public string WeightUOM { get; set; }
        public string FreightClass { get; set; }
        public string Location { get; set; }
    }
}
