//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressReleasePreview
    {
        public int PressReleasePreviewID { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string ReleaseTitle { get; set; }
        public string ReleaseText { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
