//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Press_Clippings
    {
        public int id { get; set; }
        public int Kenmark_Collections_Like_ID { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string magazine { get; set; }
        public string main_image { get; set; }
        public string inside_image { get; set; }
        public string pdf { get; set; }
        public Nullable<bool> enabled { get; set; }
    }
}
