//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicity_items
    {
        public int publicity_item_id { get; set; }
        public string Brand { get; set; }
        public string Subtitle { get; set; }
        public int Sequence { get; set; }
        public string Image_path { get; set; }
        public System.DateTime Insert_date { get; set; }
    }
}
