//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class regional_manager
    {
        public byte regional_manager_id { get; set; }
        public string region { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string background { get; set; }
        public string email { get; set; }
        public string image_name { get; set; }
        public byte sort_order { get; set; }
        public bool active { get; set; }
    }
}
