//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public string Region1 { get; set; }
        public string Description { get; set; }
        public string EmailAddress { get; set; }
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string InsideOrOutside { get; set; }
        public string ReceiveReports { get; set; }
    }
}
