//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class registered_users
    {
        public string kenmark_id { get; set; }
        public string customer_name { get; set; }
        public string salesperson_email { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public System.DateTime last_login { get; set; }
        public int customer_id { get; set; }
    }
}
