//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionSummary
    {
        public string Region { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Salesperson { get; set; }
        public string YYYYMM { get; set; }
        public string Month { get; set; }
        public Nullable<decimal> GrossSales { get; set; }
        public Nullable<decimal> GrossSalesLY { get; set; }
        public Nullable<decimal> Returns { get; set; }
        public Nullable<decimal> ReturnsLY { get; set; }
        public Nullable<decimal> NetSales { get; set; }
        public Nullable<decimal> NetSalesLY { get; set; }
        public Nullable<decimal> StockOrders { get; set; }
        public Nullable<decimal> StockOrdersLY { get; set; }
        public Nullable<decimal> NewAccounts { get; set; }
        public Nullable<decimal> NewAccountsLY { get; set; }
        public Nullable<decimal> Goals { get; set; }
        public Nullable<decimal> OpenOrders { get; set; }
        public Nullable<decimal> OnlineOrders { get; set; }
        public Nullable<decimal> Estimate { get; set; }
        public int HasEstimate { get; set; }
    }
}
