//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACFAN
    {
        public string CustomerNumber { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> CreditMemos { get; set; }
        public Nullable<decimal> ReturnedFrameUnits { get; set; }
        public Nullable<decimal> OtherSales { get; set; }
        public Nullable<decimal> SalespersonSales { get; set; }
        public Nullable<decimal> CreditSales { get; set; }
        public Nullable<decimal> OtherOrders { get; set; }
        public Nullable<decimal> SalespersonOrders { get; set; }
    }
}
