//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACMMSTemp
    {
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string Collection { get; set; }
        public string Division { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> SalesLvl0 { get; set; }
        public Nullable<decimal> SalesLvl1 { get; set; }
        public Nullable<decimal> SalesLvl2 { get; set; }
        public Nullable<decimal> SalesLvl3 { get; set; }
        public Nullable<decimal> SalesLvl4 { get; set; }
        public Nullable<decimal> SalesLvl5 { get; set; }
        public Nullable<decimal> SalesLvl6 { get; set; }
        public Nullable<decimal> SalesLvl7 { get; set; }
        public Nullable<decimal> SalesLvl8 { get; set; }
        public Nullable<decimal> SalesLvl9 { get; set; }
        public Nullable<decimal> SalesLvlBelow9 { get; set; }
        public Nullable<decimal> CreditLvl0 { get; set; }
        public Nullable<decimal> CreditLvl1 { get; set; }
        public Nullable<decimal> CreditLvl2 { get; set; }
        public Nullable<decimal> CreditLvl3 { get; set; }
        public Nullable<decimal> CreditLvl4 { get; set; }
        public Nullable<decimal> CreditLvl5 { get; set; }
        public Nullable<decimal> CreditLvl6 { get; set; }
        public Nullable<decimal> CreditLvl7 { get; set; }
        public Nullable<decimal> CreditLvl8 { get; set; }
        public Nullable<decimal> CreditLvl9 { get; set; }
        public Nullable<decimal> CreditLvlBelow9 { get; set; }
        public Nullable<decimal> NewPhoneOrders { get; set; }
        public Nullable<decimal> NewStockOrders { get; set; }
        public Nullable<decimal> PhoneBO { get; set; }
        public Nullable<decimal> StockBO { get; set; }
        public Nullable<decimal> NewPhoneSales { get; set; }
        public Nullable<decimal> NewStockSales { get; set; }
        public Nullable<decimal> PhoneBOSales { get; set; }
        public Nullable<decimal> StockBOSales { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public Nullable<decimal> Quota { get; set; }
        public Nullable<decimal> BonusEligibleNetSales { get; set; }
    }
}
