//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACollection
    {
        public string Collection { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> FrameSales { get; set; }
        public Nullable<decimal> NonFrameSales { get; set; }
        public Nullable<decimal> FrameReturnSales { get; set; }
        public Nullable<decimal> NonFrameReturnSales { get; set; }
        public Nullable<decimal> FrameDefectiveReturnSales { get; set; }
        public Nullable<decimal> NonFrameDefectiveReturnSales { get; set; }
        public Nullable<decimal> FrameCost { get; set; }
        public Nullable<decimal> NonFrameCost { get; set; }
        public Nullable<decimal> FrameReturnCost { get; set; }
        public Nullable<decimal> NonFrameReturnCost { get; set; }
        public Nullable<decimal> FrameDefectiveReturnCost { get; set; }
        public Nullable<decimal> NonFrameDefectiveReturnCost { get; set; }
        public Nullable<decimal> FrameUnits { get; set; }
        public Nullable<decimal> NonFrameUnits { get; set; }
        public Nullable<decimal> FrameReturnUnits { get; set; }
        public Nullable<decimal> NonFrameReturnUnits { get; set; }
        public Nullable<decimal> FrameDefectiveReturnUnits { get; set; }
        public Nullable<decimal> NonFrameDefectiveReturnUnits { get; set; }
        public Nullable<decimal> FrameFirstOrderUnits { get; set; }
        public Nullable<decimal> NonFrameFirstOrderUnits { get; set; }
        public Nullable<decimal> FrameFirstShipUnits { get; set; }
        public Nullable<decimal> NonFrameFirstShipUnits { get; set; }
        public Nullable<decimal> ConsignmentSales { get; set; }
        public Nullable<decimal> ConsignmentUnits { get; set; }
        public Nullable<decimal> OutsideFrameSales { get; set; }
        public Nullable<decimal> OutsideNonFrameSales { get; set; }
        public Nullable<decimal> OutsideFrameReturnSales { get; set; }
        public Nullable<decimal> OutsideNonFrameReturnSales { get; set; }
        public Nullable<decimal> OutsideFrameDefectiveReturnSales { get; set; }
        public Nullable<decimal> OutsideNonFrameDefectiveReturnSales { get; set; }
        public Nullable<decimal> OutsideFrameCost { get; set; }
        public Nullable<decimal> OutsideNonFrameCost { get; set; }
        public Nullable<decimal> OutsideFrameReturnCost { get; set; }
        public Nullable<decimal> OutsideNonFrameReturnCost { get; set; }
        public Nullable<decimal> OutsideFrameDefectiveReturnCost { get; set; }
        public Nullable<decimal> OutsideNonFrameDefectiveReturnCost { get; set; }
        public Nullable<decimal> OutsideFrameUnits { get; set; }
        public Nullable<decimal> OutsideNonFrameUnits { get; set; }
        public Nullable<decimal> OutsideFrameReturnUnits { get; set; }
        public Nullable<decimal> OutsideNonFrameReturnUnits { get; set; }
        public Nullable<decimal> OutsideFrameDefectiveReturnUnits { get; set; }
        public Nullable<decimal> OutsideNonFrameDefectiveReturnUnits { get; set; }
        public Nullable<decimal> OutsideFrameFirstOrderUnits { get; set; }
        public Nullable<decimal> OutsideNonFrameFirstOrderUnits { get; set; }
        public Nullable<decimal> OutsideFrameFirstShipUnits { get; set; }
        public Nullable<decimal> OutsideNonFrameFirstShipUnits { get; set; }
        public Nullable<decimal> OutsideConsignmentSales { get; set; }
        public Nullable<decimal> OutsideConsignmentUnits { get; set; }
        public Nullable<decimal> InsideFrameSales { get; set; }
        public Nullable<decimal> InsideNonFrameSales { get; set; }
        public Nullable<decimal> InsideFrameReturnSales { get; set; }
        public Nullable<decimal> InsideNonFrameReturnSales { get; set; }
        public Nullable<decimal> InsideFrameDefectiveReturnSales { get; set; }
        public Nullable<decimal> InsideNonFrameDefectiveReturnSales { get; set; }
        public Nullable<decimal> InsideFrameCost { get; set; }
        public Nullable<decimal> InsideNonFrameCost { get; set; }
        public Nullable<decimal> InsideFrameReturnCost { get; set; }
        public Nullable<decimal> InsideNonFrameReturnCost { get; set; }
        public Nullable<decimal> InsideFrameDefectiveReturnCost { get; set; }
        public Nullable<decimal> InsideNonFrameDefectiveReturnCost { get; set; }
        public Nullable<decimal> InsideFrameUnits { get; set; }
        public Nullable<decimal> InsideNonFrameUnits { get; set; }
        public Nullable<decimal> InsideFrameReturnUnits { get; set; }
        public Nullable<decimal> InsideNonFrameReturnUnits { get; set; }
        public Nullable<decimal> InsideFrameDefectiveReturnUnits { get; set; }
        public Nullable<decimal> InsideNonFrameDefectiveReturnUnits { get; set; }
        public Nullable<decimal> InsideFrameFirstOrderUnits { get; set; }
        public Nullable<decimal> InsideNonFrameFirstOrderUnits { get; set; }
        public Nullable<decimal> InsideFrameFirstShipUnits { get; set; }
        public Nullable<decimal> InsideNonFrameFirstShipUnits { get; set; }
        public Nullable<decimal> InsideConsignmentSales { get; set; }
        public Nullable<decimal> InsideConsignmentUnits { get; set; }
        public Nullable<decimal> ab_orders { get; set; }
        public Nullable<decimal> ef_orders { get; set; }
        public Nullable<decimal> ghkl_orders { get; set; }
        public Nullable<decimal> st_orders { get; set; }
        public Nullable<decimal> cxy_orders { get; set; }
        public Nullable<decimal> op_orders { get; set; }
        public Nullable<decimal> Outsideab_orders { get; set; }
        public Nullable<decimal> Outsideef_orders { get; set; }
        public Nullable<decimal> Outsideghkl_orders { get; set; }
        public Nullable<decimal> Outsidest_orders { get; set; }
        public Nullable<decimal> Outsidecxy_orders { get; set; }
        public Nullable<decimal> Outsideop_orders { get; set; }
        public Nullable<decimal> Insideab_orders { get; set; }
        public Nullable<decimal> Insideef_orders { get; set; }
        public Nullable<decimal> Insideghkl_orders { get; set; }
        public Nullable<decimal> Insidest_orders { get; set; }
        public Nullable<decimal> Insidecxy_orders { get; set; }
        public Nullable<decimal> Insideop_orders { get; set; }
    }
}
