//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACSFNTemp
    {
        public string CustomerNumber { get; set; }
        public string ShipTo { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> CreditMemoInvoices { get; set; }
        public Nullable<decimal> FrameUnitsReturned { get; set; }
        public Nullable<decimal> OtherSalesDollars { get; set; }
        public Nullable<decimal> SalespersonSalesDollars { get; set; }
        public Nullable<decimal> CreditSalesDollars { get; set; }
        public Nullable<decimal> OtherOrderDocuments { get; set; }
        public Nullable<decimal> SalespersonOrderDocuments { get; set; }
    }
}
