//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACSF
    {
        public string CustomerNumber { get; set; }
        public string ShipTo { get; set; }
        public string Style { get; set; }
        public string ColorCode { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> OtherFrameUnits { get; set; }
        public Nullable<decimal> SalespersonFrameUnits { get; set; }
    }
}
