//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACUST
    {
        public string CustomerNumber { get; set; }
        public string Division { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CreditSales { get; set; }
        public Nullable<decimal> CreditCost { get; set; }
    }
}
