//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACUSO
    {
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string CustomerNumber { get; set; }
        public string ShipTo { get; set; }
        public string YYYYMM { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> OrderedAmount { get; set; }
        public string Qualify { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    }
}
