//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAGoal
    {
        public string Salesperson { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> SalesEstimate { get; set; }
        public Nullable<decimal> SalesTarget { get; set; }
        public Nullable<decimal> StockTarget { get; set; }
    }
}
