//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleFrame
    {
        public string sku { get; set; }
        public Nullable<decimal> sale_percent { get; set; }
        public string is_flash_sale { get; set; }
        public string flash_expires { get; set; }
    }
}
