//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        public string Salesperson1 { get; set; }
        public string SalespersonCategory { get; set; }
        public string SalespersonName { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
        public Nullable<decimal> MtdSalesDollars { get; set; }
        public Nullable<decimal> MtdCostsDollars { get; set; }
        public Nullable<decimal> YtdSalesDollars { get; set; }
        public Nullable<decimal> YtdCostsDollars { get; set; }
        public Nullable<decimal> PyrSalesDollars { get; set; }
        public Nullable<decimal> PyrCostsDollars { get; set; }
        public Nullable<decimal> Level1CommissionPercent { get; set; }
        public Nullable<decimal> Level2CommissionPercent { get; set; }
        public Nullable<decimal> Level3CommissionPercent { get; set; }
        public Nullable<decimal> Level4CommissionPercent { get; set; }
        public Nullable<decimal> Level5CommissionPercent { get; set; }
        public Nullable<decimal> Level6CommissionPercent { get; set; }
        public string AlphaSort { get; set; }
        public Nullable<decimal> BelowLevel9CommissionPercent { get; set; }
        public Nullable<decimal> BelowLevel6QuotaPercent { get; set; }
        public string Telemarketing { get; set; }
        public string LocalRegion { get; set; }
        public Nullable<decimal> Level7CommissionPercent { get; set; }
        public Nullable<decimal> Level8CommissionPercent { get; set; }
        public Nullable<decimal> Level9CommissionPercent { get; set; }
        public string EmailAddress { get; set; }
        public string Note { get; set; }
        public string BonusProgram { get; set; }
        public string CreditHoldInformation { get; set; }
        public Nullable<decimal> FlatCommissionRate { get; set; }
        public string DefaultAnswers { get; set; }
        public string VoiceMail { get; set; }
    }
}
