//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASCOL
    {
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string YYYYMM { get; set; }
        public string Collection { get; set; }
        public Nullable<decimal> StockOrderSales { get; set; }
        public Nullable<decimal> StockOrderCost { get; set; }
        public Nullable<decimal> OtherSales { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> ReturnSales { get; set; }
        public Nullable<decimal> ReturnCost { get; set; }
        public Nullable<decimal> DefReturnSales { get; set; }
        public Nullable<decimal> DefReturnCost { get; set; }
        public Nullable<decimal> ConsignmentSales { get; set; }
        public Nullable<decimal> StockOrderUnits { get; set; }
        public Nullable<decimal> OtherUnits { get; set; }
        public Nullable<decimal> ReturnUnits { get; set; }
        public Nullable<decimal> DefReturnUnits { get; set; }
        public Nullable<decimal> ConsignmentUnits { get; set; }
    }
}
