//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASLSP
    {
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string Division { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> StockOrders { get; set; }
        public Nullable<decimal> PhoneOrders { get; set; }
        public Nullable<decimal> PhoneSales { get; set; }
        public Nullable<decimal> StockSales { get; set; }
        public Nullable<decimal> CreditSales { get; set; }
        public Nullable<decimal> CreditCost { get; set; }
        public Nullable<decimal> StockCredits { get; set; }
        public Nullable<decimal> PhoneCredits { get; set; }
        public Nullable<decimal> ReturnStockSales { get; set; }
        public Nullable<decimal> CreditStockSales { get; set; }
    }
}
