//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASummary
    {
        public string Salesperson { get; set; }
        public string SalespersonCategory { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> NewReactivatedAccounts { get; set; }
        public Nullable<decimal> StockOrders { get; set; }
        public Nullable<decimal> PhoneOrders { get; set; }
        public string Region { get; set; }
    }
}
