//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASVCR
    {
        public string Style { get; set; }
        public string Item { get; set; }
        public string YYYYMM { get; set; }
        public Nullable<decimal> ServiceDays { get; set; }
        public Nullable<decimal> WorkDays { get; set; }
        public string Collection { get; set; }
        public string LikeCollection { get; set; }
        public string VendorNumber { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> Committed { get; set; }
        public Nullable<decimal> OnOrder { get; set; }
        public Nullable<decimal> OnHandEOM { get; set; }
        public Nullable<decimal> CostEOM { get; set; }
    }
}
