//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class securityBAK
    {
        public int security_id { get; set; }
        public int customer_id { get; set; }
        public string user_type { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string secret_question { get; set; }
        public string secret_answer { get; set; }
        public short security_level { get; set; }
        public string email_address { get; set; }
        public System.DateTime user_added { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public System.DateTime last_login { get; set; }
        public string added_by { get; set; }
        public string user_group { get; set; }
    }
}
