//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_ScansVEW2013
    {
        public int id { get; set; }
        public string Device_Number { get; set; }
        public string Booth_Number { get; set; }
        public string Show_Name { get; set; }
        public string Salesperson { get; set; }
        public string First_Name_Prefix { get; set; }
        public string First_name { get; set; }
        public string Middile_Initials { get; set; }
        public string Last_Name { get; set; }
        public string Last_Name_Suffix { get; set; }
        public string Title { get; set; }
        public string Company_1 { get; set; }
        public string Company_2 { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Badge_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Registration_Category { get; set; }
        public string Position { get; set; }
        public string Type_of_Business { get; set; }
        public string User_Title { get; set; }
        public string Interested_In { get; set; }
        public string A_Lead { get; set; }
        public string B_Lead { get; set; }
        public string C_Lead { get; set; }
    }
}
