//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLSINV
    {
        public string Salesperson { get; set; }
        public string Collection { get; set; }
        public string Item { get; set; }
        public string BagLayout { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
        public Nullable<decimal> Sold { get; set; }
        public Nullable<decimal> Billed { get; set; }
        public Nullable<decimal> Charge { get; set; }
    }
}
