//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLSTran
    {
        public string Salesperson { get; set; }
        public int Line { get; set; }
        public string Type { get; set; }
        public string Item { get; set; }
        public Nullable<int> Qty { get; set; }
        public string CustomerNumber { get; set; }
        public string ShipTo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Notes { get; set; }
        public string DestSalesperson { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> LinkedTrans { get; set; }
        public string Replenish { get; set; }
        public string SendCase { get; set; }
    }
}
