//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staff_id { get; set; }
        public string staff_title { get; set; }
        public string staff_name { get; set; }
        public string staff_email { get; set; }
        public Nullable<byte> team_id { get; set; }
        public bool active { get; set; }
    }
}
