//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int statement_id { get; set; }
        public string accountnumber { get; set; }
        public decimal amountcurrent { get; set; }
        public decimal pastdue1 { get; set; }
        public decimal pastdue2 { get; set; }
        public decimal pastdue3 { get; set; }
        public decimal pastdue4 { get; set; }
        public decimal amounttotal { get; set; }
        public string message { get; set; }
        public System.DateTime insert_date { get; set; }
    }
}
