//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stmt_aging
    {
        public string kenmark_id { get; set; }
        public Nullable<decimal> total_balance { get; set; }
        public Nullable<decimal> current_balance { get; set; }
        public Nullable<decimal> balance_1to30 { get; set; }
        public Nullable<decimal> balance_31to60 { get; set; }
        public Nullable<decimal> balance_61_90 { get; set; }
        public Nullable<decimal> over90_balance { get; set; }
    }
}
