//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stmt_details90
    {
        public string invoice_number { get; set; }
        public int invoice_line_number { get; set; }
        public string customer_po { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<decimal> total_invoice { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> freight { get; set; }
        public string kenmark_id { get; set; }
        public string terms { get; set; }
        public string ship_via { get; set; }
        public Nullable<int> shipped_qty { get; set; }
        public Nullable<int> backordered_qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string item_number { get; set; }
        public string description { get; set; }
        public string special_pricing_flag { get; set; }
        public string shipto_name { get; set; }
        public string shipto_address1 { get; set; }
        public string shipto_address2 { get; set; }
        public string shipto_address3 { get; set; }
        public string document_number { get; set; }
        public Nullable<decimal> list_price { get; set; }
        public string sold_to { get; set; }
    }
}
