//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPerformance
    {
        public string Salesperson { get; set; }
        public string Style { get; set; }
        public Nullable<decimal> Sold { get; set; }
        public int BagQty { get; set; }
        public int Value { get; set; }
    }
}
