//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporary_Customers
    {
        public int tempid { get; set; }
        public int rep_security_id { get; set; }
        public string kenmark_id { get; set; }
        public string OwnerName { get; set; }
        public string BuyerName { get; set; }
        public string BusinessName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SalesTerritory { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string BuyingGroup { get; set; }
    }
}
