//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporary_ShipTo
    {
        public int sID { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public string TempCustomer_ID { get; set; }
        public string Ship_to_Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string shipTo_ID { get; set; }
        public string rep_securityID { get; set; }
        public string Phone { get; set; }
    }
}
