//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextAlert_Numbers
    {
        public string security_id { get; set; }
        public string number { get; set; }
        public string group { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
