//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Used_Promo_Codes
    {
        public int CustomerID { get; set; }
        public string Promo_Code { get; set; }
        public Nullable<System.DateTime> Date_Used { get; set; }
    }
}
