//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Security { get; set; }
        public string Restriction { get; set; }
        public string Title { get; set; }
        public string Extensions { get; set; }
        public string EMail { get; set; }
    }
}
