//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUser
    {
        public Nullable<decimal> SEQ { get; set; }
        public string ID { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public string Region { get; set; }
        public string Salesperson { get; set; }
        public string Customer { get; set; }
        public string Vendor { get; set; }
        public string EMail { get; set; }
        public string PWChangeReq { get; set; }
        public string Acctg { get; set; }
    }
}
