//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_fcdFrameSize
    {
        public Nullable<int> lSize_sk { get; set; }
        public Nullable<int> lFrame_sk { get; set; }
        public string sEye_sz { get; set; }
        public string sA_sz { get; set; }
        public string sB_sz { get; set; }
        public string sC_sz { get; set; }
        public string sED_sz { get; set; }
        public string sDBL_sz { get; set; }
        public string sTemple_sz { get; set; }
        public string sTempleDesc_tx { get; set; }
        public string sCircumference_sz { get; set; }
        public string sBridge_sz { get; set; }
        public System.DateTime backupdate { get; set; }
    }
}
