//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_fcdFrameUPC
    {
        public int lUPCLink_sk { get; set; }
        public string UPC { get; set; }
        public string SKU { get; set; }
        public Nullable<int> lMnI_sk { get; set; }
        public Nullable<int> lFrame_sk { get; set; }
        public Nullable<int> lFrameColor_sk { get; set; }
        public Nullable<int> lSize_sk { get; set; }
        public System.DateTime backupdate { get; set; }
    }
}
