//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_fcdFrames
    {
        public int lFrame_sk { get; set; }
        public Nullable<int> lMI_sk { get; set; }
        public string szMfgName_tx { get; set; }
        public string sName_tx { get; set; }
        public Nullable<int> lSeries_sk { get; set; }
        public string sSeries_nm { get; set; }
        public Nullable<int> lProductGroup_sk { get; set; }
        public string sProductGroup_tx { get; set; }
        public Nullable<short> iStatus { get; set; }
        public string iVolume_no { get; set; }
        public string iPage_no { get; set; }
        public Nullable<int> lCountry_sk { get; set; }
        public string sCountry_tx { get; set; }
        public Nullable<int> lBridge_sk { get; set; }
        public string sBridge_tx { get; set; }
        public string sBridgeInfo_tx { get; set; }
        public Nullable<int> lTemple_sk { get; set; }
        public string sTemple_tx { get; set; }
        public string sTempleInfo_tx { get; set; }
        public Nullable<int> lLens_sk { get; set; }
        public string sLens_tx { get; set; }
        public string sLensInfo_tx { get; set; }
        public Nullable<int> lMaterial_sk { get; set; }
        public string sMaterial_tx { get; set; }
        public string sMaterialInfo_tx { get; set; }
        public Nullable<int> lRim_sk { get; set; }
        public string sRim_tx { get; set; }
        public Nullable<int> lGender_sk { get; set; }
        public string sGender_tx { get; set; }
        public string sGenderInfo_tx { get; set; }
        public Nullable<int> lTrim_sk { get; set; }
        public string sTrim_tx { get; set; }
        public string sTrimInfo_tx { get; set; }
        public Nullable<int> lSunglass_sk { get; set; }
        public string sSunglass_tx { get; set; }
        public Nullable<short> bImage_fl { get; set; }
        public Nullable<short> bNew_fl { get; set; }
        public string sMonthIntro_tx { get; set; }
        public string sYearIntro_tx { get; set; }
        public Nullable<double> mPrice_amt { get; set; }
        public string sOldFrame_num { get; set; }
        public Nullable<short> iBlocks_cnt { get; set; }
        public Nullable<short> bPrice_fl { get; set; }
        public Nullable<short> bDisc_fl { get; set; }
        public Nullable<short> iVWI_fl { get; set; }
        public Nullable<bool> new_frame { get; set; }
        public Nullable<System.DateTime> backupdate { get; set; }
    }
}
