//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_fcdFrameLensColor
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> LensColorID { get; set; }
        public Nullable<int> FrameColorID { get; set; }
        public string LensColor { get; set; }
        public string ManufacturerColor { get; set; }
        public string ManufacturerLensColor { get; set; }
        public System.DateTime backupdate { get; set; }
    }
}
