//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenmark_Consumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_fcdFrameColor
    {
        public int lFrameColor_sk { get; set; }
        public Nullable<int> lFrame_sk { get; set; }
        public Nullable<int> lColor_sk { get; set; }
        public string sColor_tx { get; set; }
        public string sGenericColor_tx { get; set; }
        public string sFramesColor_tx { get; set; }
        public string sFramesColor_cd { get; set; }
        public Nullable<short> iSortOrder_cnt { get; set; }
        public Nullable<short> bImage_fl { get; set; }
        public string sImageFile_nm { get; set; }
        public string sSuffix_tx { get; set; }
        public Nullable<short> bImage3d_fl { get; set; }
        public string sImageFile3d_nm { get; set; }
        public string sManufacturerColor { get; set; }
        public Nullable<int> iMfrColorFirst { get; set; }
        public System.DateTime backupdate { get; set; }
    }
}
